### ISSUE TITLE
EnchantingTable Particle is not working properly.

### ISSUE THREAD

**Issue by JUSTaMod** [ArchonKlaus/UltimateParticles#3]
The enchantingtable particle does not work. It gives the particle effect of the good 'ol update block instead.

PM Version - 4.0.0+dev.1456 (As well as 3.2.3)

**Comment by ArchonKlaus** [comment]
Ok I will fix. Thanks for the issue!

**Comment by JUSTaMod** [comment]
Looks like this was user error. Don't know how I managed to not notice my terrible spelling... but... the plugin is working as intended! lol
