### ISSUE TITLE
Loads but doesn't work

### ISSUE THREAD

**Issue by xXRyzen** [ArchonKlaus/UltimateParticles#4]
**Describe the bug**
Plugin loads fine but does not spawn particles in game

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ArchonKlaus** [comment]
Change the world's name on the particles .yml file.

**Comment by FienixEC** [comment]
No particles.yml is generated when restarting server

**Comment by ArchonKlaus** [comment]
the particle .yml is ejector.yml
